# POST http://localhost:8080/api/todo HTTP/1.1
# content-type: application/json

# {
#     "task": "Meet the tailor",
#     "completed": true,
#     "startdate": "2022-09-05T11:00:00Z",
#     "enddate": "2022-09-05T13:00:00Z"
# }

# GET http://localhost:8080/api/todos HTTP/1.1

# PUT http://localhost:8080/api/todo/1 HTTP/1.1
# content-type: application/json

# {
#      "task": "Take the dimensions",
#      "completed": false,
#      "startdate": "2022-09-05T16:00:00Z",
#      "enddate": "2022-09-05T18:00:00Z"
# }

DELETE http://localhost:8080/api/todo/2 HTTP/1.1